import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/contexts/AuthProvider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { messagesMap } from "../../../messages";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import AppLayout from "@/components/AppLayout";
import LocaleProvider from "@/contexts/LocaleProvider";
import ReactQueryProvider from "@/contexts/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params : Promise<{locale: string}>;
}

export default async function LocaleLayout({children, params}: Props) {

  const {locale} = await params;
  if(!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang="en">
      <body>
      <NextIntlClientProvider locale={locale} messages={messagesMap[locale]}>
        <LocaleProvider>
        <AuthProvider>
          <ReactQueryProvider>
          <AppLayout>
        {children}
        </AppLayout>
        </ReactQueryProvider>
        </AuthProvider>
        </LocaleProvider>
      </NextIntlClientProvider>

      </body>
    </html>
  );
}
