export enum LoanStatusEnum {
    PENDING = 'PENDING',
    ADVISOR_APPROVED = 'ADVISOR_APPROVED',
    ADVISOR_REJECTED = 'ADVISOR_REJECTED',
    DIRECTOR_APPROVED = 'DIRECTOR_APPROVED',
    DIRECTOR_REJECTED = 'DIRECTOR_REJECTED',
    RATE_PROPOSED = 'RATE_PROPOSED',
    CLIENT_REJECTED = 'CLIENT_REJECTED',
    DISBURSED = 'DISBURSED',
    PAID_OFF = 'PAID_OFF'
}