export enum PermissionEnum {
    VIEW_ACCOUNTS = 'VIEW_ACCOUNTS',
    TRANSFER_FUNDS = 'TRANSFER_FUNDS',
    APPROVE_LOANS = 'APPROVE_LOANS',
    CREATE_ACCOUNTS = 'CREATE_ACCOUNTS',
    CLOSE_ACCOUNTS = 'CLOSE_ACCOUNTS',
    MANAGE_USERS = 'MANAGE_USERS',
    VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
    CREATE_STOCK_ORDERS = 'CREATE_STOCK_ORDERS',
    VIEW_LOANS = 'VIEW_LOANS',
    MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',
    READ_MESSAGES = 'READ_MESSAGES',
    SEND_MESSAGES = 'SEND_MESSAGES',
}